// ==UserScript==
// @name         Tableau Doctor UI Improvements
// @namespace    http://tampermonkey.net/
// @version      0.2
// @description  Improve the Tableau Doctor Experience by improving the overall UI
// @author       Asher Cambpell
// @match        https://*.visual.force.com/apex/tdworkorder*
// @require		 https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js
// ==/UserScript==
/* jshint -W097 */
'use strict';

// Your code here...

(function() {
    var starting_value = { 'event' : 'TC17 Las Vegas'
                         , 'area' : 'Traditional Tableau Doctor'
                         , 'language_select' : 'English'
                         };

    // Set Area and Event values to their intitial states
    $($('select')[0]).val(starting_value.event);
    $($('select')[1]).val(starting_value.area);
    $($('select')[2]).val(starting_value.language_select);
    
    //var language_label = $('<label>').html('Preferred Language:');
    // BUGBUGBUG salesforce 
    var language_select = $('.requiredBlock+Select');
    //var language_select = $('<select>');
    console.log(language_select);
    language_select.addClass('language_select');
    //language_select.append($('<option>').attr('value', 'English').html('English'));
    //language_select.append($('<option>').attr('value', 'French').html('French'));
    //language_select.append($('<option>').attr('value', 'German').html('German'));
    //language_select.append($('<option>').attr('value', 'Portuguese').html('Portuguese'));
    //language_select.append($('<option>').attr('value', 'Spanish').html('Spanish'));
    //language_select.append($('<option>').attr('value', 'Mandarin').html('Mandarin'));
    //language_select.append($('<option>').attr('value', 'Korean').html('Korean'));
    //language_select.append($('<option>').attr('value', 'Japanese').html('Japanese'));
    //language_label.append(language_select);

    // List of Doctors
    var doctors_list = [ 'Aaron Vandervort'
                       , 'Aaron Volosin'
                       , 'Adam Cook'
                       , 'Alan Eldridge'
                       , 'Alexis Guinebertiere'
                       , 'Ali Kherani'
                       , 'Allan McMordie'
                       , 'Alysa Little'
                       , 'Amanda Luthy'
                       , 'Amy Mietkiewicz'
                       , 'Andrew Furdell'
                       , 'Andrew Kemp'
                       , 'Ankur Jethi'
                       , 'Anna Lee'
                       , 'Anthony Vazquez'
                       , 'Anthony Young'
                       , 'Aria Jelinek'
                       , 'Arman Kehlhofer'
                       , 'Asher Campbell'
                       , 'Ashlyn Opgrande'
                       , 'Austin Dahl'
                       , 'Bemnet Merha'
                       , 'Ben Prostor'
                       , 'Benjamin Vanlom'
                       , 'Bethany Lyons'
                       , 'BJ Bjostad'
                       , 'BK Chung'
                       , 'Blake Thomson'
                       , 'Boas Lee'
                       , 'Bob Warwood'
                       , 'Bora Beran'
                       , 'Brad Shuel'
                       , 'Brandi Gutfriend'
                       , 'Brandon Babbitt'
                       , 'Brandon Hawkins'
                       , 'Brent Bateman'
                       , 'Brett Megaard'
                       , 'Brett Taylor'
                       , 'Brett Webber'
                       , 'Brian Chapman'
                       , 'Brian O\'Connor'
                       , 'Brian Russell'
                       , 'Brian Seeley'
                       , 'Bronson Shonk'
                       , 'Bryan Caldwell'
                       , 'Bryan Medeiros'
                       , 'Bryant Howell'
                       , 'Carlton Findley'
                       , 'Cassius Butcher'
                       , 'Celeste Luna'
                       , 'Charles Vaughn'
                       , 'Charley McGee'
                       , 'Chase Culver'
                       , 'Chris Beck'
                       , 'Chris Bullock'
                       , 'Chris Eubank'
                       , 'Chris Jones'
                       , 'Christie Clark'
                       , 'Christine Klemp'
                       , 'CJ Callender'
                       , 'Clark Eklund'
                       , 'Clark Hodder'
                       , 'Colby Pash'
                       , 'Colin Merry'
                       , 'Cor Bader'
                       , 'Courtney Drake'
                       , 'Curt Budd'
                       , 'Dan Cory'
                       , 'Dan Huff'
                       , 'Dan Leventhal'
                       , 'Dan Stokes'
                       , 'Daniel Berlin'
                       , 'Darren McGurran'
                       , 'Dave Pace'
                       , 'David Chow'
                       , 'David Ciam'
                       , 'David Petranek'
                       , 'David Sears'
                       , 'Deepti Lnu'
                       , 'Derek Cyr'
                       , 'Dirk Karis'
                       , 'Doug Carter'
                       , 'Dylan Lockman'
                       , 'Ehab Elgohary'
                       , 'Emiliano Colosimo'
                       , 'Eric Chen'
                       , 'Eric Veal'
                       , 'Erik Pearson'
                       , 'Erik Polano'
                       , 'Erik Teutsch'
                       , 'Erwin van Laar'
                       , 'Esther Aller'
                       , 'Ethan Rice'
                       , 'Evan Alini'
                       , 'Evandro Pacolla'
                       , 'Fernando Villanueva Armenta'
                       , 'Geoffrey Petit'
                       , 'Gerard Valerio'
                       , 'Gil Gani'
                       , 'Giovanni Alvarado'
                       , 'Grace Labriola'
                       , 'Greg Filpus'
                       , 'Greg Kennedy'
                       , 'Guilherme de Menezes Duarte'
                       , 'Harshit Gupta'
                       , 'Hermann Chong'
                       , 'Heyward Drummond'
                       , 'Hieu Do'
                       , 'Hildebrando Mangabeira de Souza'
                       , 'Howard Morgenstern'
                       , 'Hugh Nguyen'
                       , 'Isaac Minor'
                       , 'Jacob Sherman'
                       , 'Jacob Thiede'
                       , 'Jagjit Singh'
                       , 'James Baker'
                       , 'James Davis'
                       , 'James Parsons'
                       , 'James Ryan'
                       , 'Jason Weill'
                       , 'Jay Hickerson'
                       , 'Jazmyn Li'
                       , 'Jeff Wallace'
                       , 'Jeremiah Darais'
                       , 'Jeremy Mayo'
                       , 'Jeremy Weatherall'
                       , 'Jiesi Zhao'
                       , 'Joaquin Luna'
                       , 'Joe O\'Brian'
                       , 'Joel Hutchison'
                       , 'John Barnes'
                       , 'John Cahill'
                       , 'John Dobrosielski'
                       , 'John McIntyre'
                       , 'Jon Dugger'
                       , 'Jon Munger'
                       , 'Josh Davis'
                       , 'Josh Weyburne'
                       , 'Joshua Rauh'
                       , 'Julian Kelly'
                       , 'Juracy Americo De Oliveira Filho'
                       , 'Justin Craycraft'
                       , 'Kaifeng Zeng'
                       , 'Keith Schultz'
                       , 'Kenny Jun Hong Lee'
                       , 'Kevin Hulbert'
                       , 'Kevin Immink'
                       , 'Kevin Krizek'
                       , 'Kyle Bohac'
                       , 'Larry Hill'
                       , 'Lauren Beck'
                       , 'Lee Bond-Kennedy'
                       , 'Linus Willson'
                       , 'Luca Bandini'
                       , 'Lucky Tiffany'
                       , 'Luis Enciso'
                       , 'Luke Ibsen'
                       , 'Manish Tripathi'
                       , 'Mark Santino'
                       , 'Marut Veerawatyotin'
                       , 'Matt Gizbert'
                       , 'Michael Becke'
                       , 'Michael Cox'
                       , 'Michael Moncavage'
                       , 'Miguel Habib'
                       , 'Minji Kim'
                       , 'Mitchell Landis'
                       , 'Mrunal Shridhar'
                       , 'Naisan Geula'
                       , 'Nazirah Garrison'
                       , 'Nena Ballas'
                       , 'Nick Hara'
                       , 'Nick Hritsko'
                       , 'Nick Speck'
                       , 'Obed Tsimi'
                       , 'Paul Cardon'
                       , 'Paul Isaacs'
                       , 'Rachel Hirsch'
                       , 'Rafi Zelikowsky'
                       , 'Rakhi Harkawat'
                       , 'Ray Randall'
                       , 'Richard Durval'
                       , 'Richard Wilson'
                       , 'Rithesh Makkena'
                       , 'Rob Barnhart'
                       , 'Robert Calvert'
                       , 'Robert DuPont'
                       , 'Roger Dubbs'
                       , 'Roger Hau'
                       , 'Rosana Tran'
                       , 'Rosie Chkodrova'
                       , 'Roslyn Garcia'
                       , 'Ross Paulson'
                       , 'Russ Goldin'
                       , 'Ryan Jimenez'
                       , 'Ryan Lempa'
                       , 'Ryan Wagner'
                       , 'Samuel Osborn'
                       , 'Sandeep Srinivasan'
                       , 'Sanjay Shah'
                       , 'Sara Kelly'
                       , 'Sara Rantschler'
                       , 'Sara Sparks'
                       , 'Sarah Nell'
                       , 'Scott DeMers'
                       , 'Sean Sullivan'
                       , 'Sergio Sanchez'
                       , 'Shailesh Kumar'
                       , 'Shawn Pfaff'
                       , 'Shirley Reagor'
                       , 'Shivi Rayaprolu'
                       , 'Stephane D\'Avril-Favreau'
                       , 'Stephen Price'
                       , 'Steve Farrell'
                       , 'Steve Martinez'
                       , 'Steven Mostello'
                       , 'Stoyko Kostov'
                       , 'Susan Zhang'
                       , 'Sy Lighthill'
                       , 'Terence Soh'
                       , 'Terrence Maas'
                       , 'Timo Tautenhahn'
                       , 'Tony Kao'
                       , 'Travis Watt'
                       , 'Trevor Crandall'
                       , 'Trevor Hall'
                       , 'Tri Tu'
                       , 'Tristan Mikoleit'
                       , 'Tyler Reeves'
                       , 'Vien Hua'
                       , 'Vikram Bandarupalli'
                       , 'Vishaal Kapoor'
                       , 'Vlad Usatin'
                       , 'Will Pitzler'
                       , 'William Baughman'
                       , 'William Pugh'
                       , 'Wilson Po'
                       , 'Xingchi Cheng'
                       , 'Zach Pipkin'
                       , 'Zachary Matthews'
                       , 'Name Not Listed'
    ];

    // Hide original Doctor input, and control it's value with a select box populated from aboev list.
    var orig_input = $($('.requiredBlock')[0]).siblings('input');
    console.log(orig_input.length);
    var doctor_select = $('<select>');
    doctor_select.append($('<option>').attr('value', '').html('Select a Doctor'));
    for (var d = 0; d < doctors_list.length; d++) {
        doctor_select.append($('<option>').attr('value', doctors_list[d]).html(doctors_list[d]));
    }
    orig_input.after(doctor_select);
    orig_input.hide();
    doctor_select.val(orig_input.val());

    doctor_select.change(function() {
        orig_input.val(doctor_select.val());
    });      
})();